complete -c gist -f -a "create"  -d "Creates a new gist"
complete -c gist -f -a "edit"    -d "Edit the files in your gist"
complete -c gist -f -a "list"    -d "Prints a list of your gists"
complete -c gist -f -a "clone"   -d "Clones a gist"
complete -c gist -f -a "delete"  -d "Deletes a gist from GitHub"
complete -c gist -f -a "files"   -d "Prints a list of the files in a gist"
complete -c gist -f -a "archive" -d "Downloads a gist and creates a tarball"
complete -c gist -f -a "content" -d "Pints the content of the gist to stdout"
complete -c gist -f -a "info"    -d "Prints detailed information about a gist"
complete -c gist -f -a "version" -d "Pints the current version"