complete -c create -d "Creates a new gist"
complete -c edit -d "Edit the files in your gist"
complete -c list -d "Prints a list of your gists"
complete -c clone -d "Clones a gist"
complete -c delete -d "Deletes a gist from github"
complete -c files -d "Prints a list of the files in a gist"
complete -c archive -d "Ownloads a gist and creates a tarball"
complete -c content -d "Rints the content of the gist to stdout"
complete -c info -d "Prints detailed information about a gist"
complete -c version -d "Rints the current version"